version: '3.7'

services:

  nginx:
    container_name: exo_devops_nginx
    build: docker/nginx
    volumes:
      - ./app/:/var/www/html/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

  php-fpm:
    container_name: exo_devops_php
    build: docker/php-fpm
    volumes:
      - ./app/:/var/www/html/
      - ./docker/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost

  mariadb:
    container_name: exo_devops_mariadb
    image: mariadb:10.7
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=exo_devops
    ports:
      - "3306:3306"
