name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-docker-image .

      - name: Start Docker Compose
        run: |
          docker-compose up -d 
          sleep 10 # Wait for MySQL to start up
          
      - name: Run tests
        run: |
          docker exec my-container-name php test.php

      - name: Create table in database
        run: |
          docker exec -e MYSQL_ROOT_PASSWORD=root my-mariadb-container-name sh -c 'exec mysql -uroot -proot my-database-name -e "CREATE TABLE my-table-name (id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(30) NOT NULL)"'

      - name: Add data to table
        run: |
          docker exec my-mariadb-container-name sh -c "INSERT INTO my-table-name (name) VALUES ('John')"
