name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Stop and Remove mariadb container
      run: |
        docker-compose down
        docker container rm exo_devops_mariadb
      continue-on-error: true
    - name: Recreate mariadb container
      run: docker-compose up -d
    - name: Wait for mariadb container to start
      run: docker exec exo_devops_mariadb sh -c 'while ! mysqladmin ping -hlocalhost --silent; do sleep 1; done;'
      env:
        MYSQL_ROOT_PASSWORD: root
    - name: Debugging MySQL
      run: |
        docker exec exo_devops_mariadb sh -c 'ls -la /var/run/mysqld'
        docker exec exo_devops_mariadb sh -c 'ls -la /run/mysqld'
        docker exec exo_devops_mariadb sh -c 'ls -la /var/lib/mysql'
      env:
        MYSQL_ROOT_PASSWORD: root
    - name: Add table to database
      run: docker exec exo_devops_mariadb sh -c 'exec mysql -uroot -proot exo_devops -e "CREATE TABLE users (id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(30) NOT NULL)"'
    - name: Add user to table
      run: docker exec exo_devops_mariadb sh -c "INSERT INTO users (name) VALUES ('John')"
