name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-run:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build docker composer
        run: docker compose up -d
      - name: Start test Title
        run: docker exec exo_devops_php php tests/title.php
      - name: Start test connect
        run: docker exec exo_devops_php php tests/connect.php