name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t myapp:${{ github.sha }} .

      - name: Stop and remove old container
        run: |
          docker stop myapp || true
          docker rm myapp || true

      - name: Run the Docker container
        run: docker run -d --name myapp -p 8080:80 myapp:${{ github.sha }}

      - name: Wait for application to start
        run: |
          while [[ "$(curl --write-out "%{http_code}" --silent --output /dev/null localhost:8080)" != "200" ]]; do sleep 5; done

      - name: Create a database
        run: |
          docker exec -it mariadb mysql -uroot -proot -e "CREATE DATABASE mydb"

      - name: Create a table
        run: |
          docker exec -it mariadb mysql -uroot -proot mydb -e "CREATE TABLE users (id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(30) NOT NULL)"

      - name: Add user to table
        run: |
          docker exec -it mariadb mysql -uroot -proot mydb -e "INSERT INTO users (name) VALUES ('John')"
