name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-run:

    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: root
    steps:
      - uses: actions/checkout@v2
      - name: Build docker composer
        run: docker compose up -d