name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-run:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build docker composer
        run: docker compose up -d
      - name: Start test Title
        run: docker exec exo_devops_php php tests/test_title.php
      - name: Wait 30 seconds
        run: sleep 30
      - name: Start test connect
        run: docker exec exo_devops_php php tests/test_connect.php